Exe:main.o addMember.o searchMember.o modifyMember.o delMember.o printMember.o
	gcc -o Exe main.o addMember.o searchMember.o modifyMember.o delMember.o printMember.o
main.o:main.c
	gcc -c main.c	
addMember.o:addMember.c
	gcc -c addMember.c
searchMember.o:searchMember.c
	gcc -c searchMember.c
modifyMember.o:modifyMember.c
	gcc -c modifyMember.c
delMember.o:delMember.c
	gcc -c delMember.c
printMember.o:printMember.c
	gcc -c printMember.c
